### ISSUE TITLE
Possible issue with MetaData file creation.

### ISSUE THREAD

**Issue by jamhowell** [pugliathomas/powerbiscannermetadata#14]
**Describe the bug**
Power Query error on dataset refresh: 

DataFormat.Error: We found extra characters at the end of JSON input.
Details:
    Value={

This error is happening due to an issue in the MetaData_CCYY-MM-DD file.

**To Reproduce**
This error appears when trying to refresh the dataset. Note, DAX & Mashup expressions and detailed metadata enhancements are enabled in the tenant settings. There are also >100 Workspaces modified, so batches of 100 is triggered.

**Expected behavior**
Dataset refreshes succesfully.

**Screenshots**
Found the "}{" causing the error, but not sure why it is happening.
![image](https://user-images.githubusercontent.com/89925247/154799603-503af734-82f7-4b01-8b7b-f8391be9a84f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I played with the batch counts a bit to try resolve but haven't found a solution yet.

**Comment by pugliathomas** [comment]
Try removing any reference to a personal workspace, as > 100 workspaces we have seen quite a few errors. Please see #19 for more.

**Comment by pugliathomas** [comment]
We are working on a solution - stay tuned!

**Comment by pugliathomas** [comment]
Thank you all for amazing comments. We just released the v2 version that circumvents Power Automate completely and uses Power BI Dataflows.

[Solution v2](https://github.com/pugliathomas/powerbiscannermetadata/tree/main/v2%20Solution)
