### ISSUE TITLE
Duplicate for datasources in  Metadata-File

### ISSUE THREAD

**Issue by MarioGnt** [pugliathomas/powerbiscannermetadata#18]
**Describe the bug**
Power Query error on dataset refresh:

![image](https://user-images.githubusercontent.com/102664361/160815799-53844577-6fb1-4f8b-aa48-6dcab045eb5f.png)

**To Reproduce**
I pulled information out of all workspaces (excluding personal workspaces) of our tenant (~1100 Workspaces)

**Expected behavior**
Dataset refreshes successfully.

**Screenshots**
The key dataSourceInstances appears twice:
![image](https://user-images.githubusercontent.com/102664361/160816484-23d0f922-e508-4aee-afb1-e253b0400840.png)
![image](https://user-images.githubusercontent.com/102664361/160816521-d83dca8d-aa3b-4376-be70-3a99136364d7.png)

as well as the key misconfiguredDatasourceInstances":
![image](https://user-images.githubusercontent.com/102664361/160816630-e4d36775-a9b0-4e89-a4f6-97d525c0596a.png)
![image](https://user-images.githubusercontent.com/102664361/160816660-ad7d4452-779b-4ae5-a7a0-3d56478115e0.png)

**Desktop (please complete the following information):**
 Windows 10

**Comment by pugliathomas** [comment]
Thanks. I will check it out

**Comment by rvconcha** [comment]
Hi Thomas,
Same problem on here.

**Screenshot:**
![image](https://user-images.githubusercontent.com/83028525/165636647-8617afd5-6cd8-4706-878d-10741bfcb656.png)

**Comment by FrankPreusker** [comment]
+1 from my side :-/
![image](https://user-images.githubusercontent.com/74618614/169310081-31ba9c50-ec54-4e6b-bef5-680216c8b3da.png)

**Comment by ToriaVic** [comment]
Any updates or suggestions to make this work with the duplicate name issue?

**Comment by pugliathomas** [comment]
You can update the query, as the relationship goes from dataset -> datasourceinstances -> datasets.

**Comment by ToriaVic** [comment]
Thanks Tom-  Where are we updating query?  I don't see dataset or datasourceinstances tables?

**Comment by nicovillarroel** [comment]
Hello, I have the same issue.. do you know how to solve it? Thomas, you say that we need to update the query, but where? 
Thank you.
