### ISSUE TITLE
Flow Action 'Append_to_array_responseArray' failed

### ISSUE THREAD

**Issue by FrankPreusker** [pugliathomas/powerbiscannermetadata#19]
**Describe the bug**
I have done all required setup (imported the two flows, created the App + Service principle, adjusted the tenant settings). The flow is starting successfully, but in the action "Step 3_ Retrieve data" I'm getting the error message "The variable 'responseArray' has size of more than '113213046' bytes. This exceeded the maximum size '104857600' allowed." after 9 rounds. The first 8 rounds in that loop did run ok. This is a large tenant, with currently ~22k workspaces.
![image](https://user-images.githubusercontent.com/74618614/169286898-e4dc4711-f88e-4595-8b52-71b9db172dc8.png)

What can be done to get around this issue? (Seems like a flow restriction.)

**To Reproduce**
Not sure it can be reproduced.

**Comment by pugliathomas** [comment]
How many workspaces and datasets do you have in the tenant? We have noticed that very large quantities of workspaces will error it out

**Comment by pugliathomas** [comment]
Thank you all for amazing comments. We just released the v2 version that circumvents Power Automate completely and uses Power BI Dataflows.

[Solution v2](https://github.com/pugliathomas/powerbiscannermetadata/tree/main/v2%20Solution)
