### ISSUE TITLE
Duplicate Name datasourceinstances

### ISSUE THREAD

**Issue by nicovillarroel** [pugliathomas/powerbiscannermetadata#21]
Trying to connect to the Sharepoint Library, Power Query Returns this error: Duplicate Name datasourceintances. Dont know where the problem is. It seems that the JSON file has more than one entrance for dasourceinstances. 
This is the error message: 
![image](https://user-images.githubusercontent.com/42214801/177172395-2b03c258-bdce-4567-ba0b-cd2e506b0e55.png)

I am looking at the Power Query Editor and it seems that there is a problem just in the meta Step, after the content.
![image](https://user-images.githubusercontent.com/42214801/177172784-bf7ffa04-8d09-4243-b6c6-351ce0b30261.png)

Making some additional investigation, it seems that for some reasson the JSON has duplicated parts, that we show in this picture.
![image](https://user-images.githubusercontent.com/42214801/177301141-2548bf1a-e8df-487f-9445-94a75d819074.png)

If we delete the duplicated datasourceintances and misconfiguredatasourceinstances the report template works fine.
Maybe the problem is at the Flow level building the JSON file. 

Anyway to solve this other than manipulate the JSON and delete the duplicated items?
regards.

**Comment by RaulSA-M365** [comment]
Hi NIco,

We have exactly the same issue... Is there a possibility to fix it without manual intervention???

Thanks in advance

Regards,

**Comment by chenxi3115** [comment]
We encountered the same issue too. Could you please fix it? Thanks so much!

**Comment by chenxi3115** [comment]
In our case, we don't see any duplicate in the Json responses but still we are getting "duplicated name datasourceinstances" error when loading the data in

**Comment by BertyLurch** [comment]
I discovered In Step 2, you can change the "call getInfo Endpoint" step API string and remove the "&datasources=yes" part. The output will remove the datasources completely and remove the error. You can get datasources a number of other ways, so not a massive loss.

![image](https://user-images.githubusercontent.com/44639065/183852327-26cd4223-fc34-45f1-99fe-0857c2f21378.png)

**Comment by MaratAbdullaev** [comment]
Great with suggestion from @BertyLurch as a workaround.
However it would be nice if the bug was fixed.
It seems that JSON output is manipulated in Create file step by replacing some text:
![image](https://user-images.githubusercontent.com/79451654/183928480-517bfb3e-ab07-465e-8448-b5bbd955b8fa.png)

**Comment by relax528** [comment]
This error is in the scanner API itself. I took the scan Id and called the API to get the results using https://api.powerbi.com/v1.0/myorg/admin/workspaces/scanResult/######scanid######## and the datasourceInstances array appears only once. Therefore it seems there is a bug in the way the scan Results are put together. Interesting that I have 2 batches (i.e over 100 workspaces). I wonder if there is only one batch if that clears it up. I'll post back what I find.

**Comment by relax528** [comment]
OK, first finding, I added &excludeInActiveWorkspaces=True to the call modified endpoint step inside the scope for Step 1 (get modified workspace ids). I still had 2 batches but datasourceInstances only appears once and the report can refresh since the json is valid. I feel like each scan result should be in it's own file and not combined in Power Automate but instead combined in Power Query. (I'm actually going to push to SQL and extract to individual tables. But I'm getting somewhere.

**Comment by thmere** [comment]
I added the &excludeInActiveWorkspaces=True parameter but i'm still getting the same duplicate datasourceinstances error
has anyone been able to solve this once and for all?

**Comment by relax528** [comment]
@thmere 
I stopped joining the json files together and produce a single json file per scan, then updated the M code to read multiple. This is a far cleaner solution to me and avoids all of the corrupted json when combining. Hope this helps.

**Comment by thmere** [comment]
> I discovered In Step 2, you can change the "call getInfo Endpoint" step API string and remove the "&datasources=yes" part. The output will remove the datasources completely and remove the error. You can get datasources a number of other ways, so not a massive loss.
> 
> ![image](https://user-images.githubusercontent.com/44639065/183852327-26cd4223-fc34-45f1-99fe-0857c2f21378.png)

care to share some of those additional ways? will this API call give the same information? 
GET https://api.powerbi.com/v1.0/myorg/datasets/{datasetId}/datasources

**Comment by pugliathomas** [comment]
Thank you all for amazing comments. We just released the v2 version that circumvents Power Automate completely and uses Power BI Dataflows.

[Solution v2](https://github.com/pugliathomas/powerbiscannermetadata/tree/main/v2%20Solution)

**Comment by pugliathomas** [comment]
Thank you all for amazing comments. We just released the v2 version that circumvents Power Automate completely and uses Power BI Dataflows.

[Solution v2](https://github.com/pugliathomas/powerbiscannermetadata/tree/main/v2%20Solution)

**Comment by jaisonjoe** [comment]
Hi @pugliathomas : I am using your latest version and am getting the same error. Can you please help me on this?

![image](https://github.com/pugliathomas/powerbiscannermetadata/assets/8407600/7846b36a-3b28-41db-8c24-98d429a6d5a0)
