### ISSUE TITLE
Related Resources in sharepoint connector for Power Automate

### ISSUE THREAD

**Issue by dribblej** [pugliathomas/powerbiscannermetadata#3]
# Question about email associated

Hello, 

Thank you for your work on the scanner API and for helping create a useable solution to navigate this data. When I imported the power automate zip for the API call, I saw that your email is in as a related resource. What are the implications of this? It prevented me from moving forward with this solution due to my uncertainty of the future implications of this embedded relationship to your email. 

Thank you again for this great repo, 
All the best, 
Josh

**Comment by pugliathomas** [comment]
Hi @dribblej ,

Can you elaborate on the related email? I am not certain what you are referring too. 

And can you expand on "future implications of this embedded relationship"?

**Comment by pugliathomas** [comment]
Answer: 

The related resource is for SharePoint & Notifications. It is simply the connections you need to use the flow. SharePoint for saving the metadata, and notifications for when the scanner refreshes. Nothing to do with email or Outlook.
