### ISSUE TITLE
Issue in final step of the PowerAutomate flow

### ISSUE THREAD

**Issue by ewoutbarendregt** [pugliathomas/powerbiscannermetadata#6]
**Describe the bug**
The PowerAutomate Flow is running fine and returns a number of files. Some of them are quite large (66 Mb). 
In one of the final steps, the flow hangs on step 'Return Workspace Info'.

The error text:
ActionResponseTimedOut. The execution of template action 'Return_workspace_info' is failed: the client application timed out waiting for a response from service. This means that workflow took longer to respond than the alloted timeout value. The connection maintained between the client application and service will be closed and client application will get an HTTP status code 504 Gateway Timeout.

**Screenshots**
  
![image](https://user-images.githubusercontent.com/15613133/139815299-0d1be324-8c10-42bf-884f-99bff725aa08.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Edge
 - Version Version 95.0.1020.30 (Official build) (64-bit)

**Additional context**
Although the files are produced, the provided PowerBI template does not want to load them, returning error 'We found extra characters at the end of JSON input.'

The two issues might be related.

**Comment by pugliathomas** [comment]
@ewoutbarendregt can you provide the json file? 

Technically the Return Workspace info is not required for the Flow to run. 

In regards to the extra characters, I have not seen this yet. 

How many workspaces / datasets are you pulling?

Can you send a screenshot of the variables as well? 

If you want to send the json for workspace / metadata in a secure way, please let me know.

**Comment by pugliathomas** [comment]
Also, if you do have a large file for the metadata files, you can actually modify the PBI_Scanner_Refresh Flow under "modified" variable, rather than pulling the entire metadata, you can pull since the latest scan and the rest is cached. 

![image](https://user-images.githubusercontent.com/6196804/139829105-ee44db54-55d0-437f-9f48-557d4597eb98.png)

**Comment by ewoutbarendregt** [comment]
Changing the modifiedSince did the trick. everything seems to work now. 

Thanks for your support!
Ewout
