### ISSUE TITLE
Possible bug in the "dataset" report

### ISSUE THREAD

**Issue by ms9411010** [pugliathomas/powerbiscannermetadata#8]
This is a Great tool. By the way your team hosts an excellent podcast.
i am hoping you can help me with this issue:
[apiscannerbug.docx](https://github.com/pugliathomas/powerbiscannermetadata/files/7774718/apiscannerbug.docx)

In the power bi pbix file, I navigate to the Datasets tab
On the pivot table visual there are two fields on Rows - datasetname, reportname

However when i expand the datasetname, it shows me all reports in the tenant and does not filter by reportname

for eg as show in the screen shot -   when i expand my dataset "Addedvalue by state" it shows me 70 reports
when i expand another daset e.g. ERP customer file it shows me the same 70 reports.

the relationship does not seem to be working.

pls let me know if i can provide any additional information. 
thank you

**Comment by pugliathomas** [comment]
Thank you @ms9411010  - Yes, i see the relationship issue. That should be fixed in the next version. Thank you!

**Comment by pugliathomas** [comment]
Hi @ms9411010 ,

The latest update and release now has a filter on the dataset matrix, that only shows when # Reports is not blank. Report metadata does not contain table or column information, only dataset metadata. This is workaround but it displays correctly. 

Thanks!

https://github.com/pugliathomas/powerbiscannermetadata/releases/tag/Stable2

**Comment by ms9411010** [comment]
Thank You appreciate the fix/
